---
- name: Configure Apache.
  lineinfile:
    dest: "{{ apache_server_root }}/listen.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    mode: 0644
  with_items: "{{ apache_ports_configuration_items }}"
  notify: restart apache

- name: Enable Apache mods.
  copy:
    dest: "{{ apache_server_root }}/conf.d/99-ansible-{{ item }}.conf"
    content: |
      LoadModule {{ item }}_module /usr/lib64/apache2-prefork/mod_{{ item }}.so
    mode: 0644
  with_items: "{{ apache_mods_enabled }}"
  notify: restart apache

- name: Disable Apache mods
  file:
    path: "{{ apache_server_root }}/conf.d/99-ansible-{{ item }}.conf"
    state: absent
  with_items: "{{ apache_mods_disabled }}"
  notify: restart apache

- name: Check whether certificates defined in vhosts exist.
  stat: path={{ item.certificate_file }}
  register: apache_ssl_certificates
  with_items: "{{ apache_vhosts_ssl }}"
  no_log: "{{ apache_ssl_no_log }}"

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts | bool
